# Generated by Django 5.0.4 on 2024-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
