# Generated by Django 5.0.4 on 2024-05-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_user_participated_projects'),
        ('project', '0002_project_created_date_project_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='participated_projects',
            field=models.ManyToManyField(null=True, related_name='participants', to='project.project'),
        ),
    ]
