# Generated by Django 5.0.4 on 2024-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='woking_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
