# Generated by Django 5.0.4 on 2024-05-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(default='2022-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
