# Generated by Django 5.0.4 on 2024-05-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_created_date_project_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project-images/default.png', null=True, upload_to='project-images/'),
        ),
    ]
