# Generated by Django 5.0.4 on 2024-05-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project-images/default.jpg', null=True, upload_to='project-images/'),
        ),
    ]
